# Generated by Django 3.2.9 on 2021-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_register_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(default='', max_length=123)),
                ('location', models.CharField(default='', max_length=123)),
                ('av_date', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='card/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
